name: Reusable Build

on:
  workflow_call:

jobs:
  build:
    name: BUILD-JOB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: |
           echo "Building app"
           echo "Build Completed"
